Repository smileidentity/react-native, pull requests merged in 2025-04, with the labels that each got.

#92 chore: release 10.3.1
  CHANGELOG.md
  example/ios/Podfile.lock
  package.json
  react-native-smile-id.podspec
Labels: Review effort 1/5

#90 fix: kotlin version
  android/build.gradle
Labels: Stale

#94 feat: git pod
  CONTRIBUTING.md
  android/build.gradle
  android/gradle.properties
  example/ios/Podfile
  example/ios/SmileIdExample.xcodeproj/project.pbxproj
  react-native-smile-id.podspec
Labels: Review effort 2/5

#95 chore: release prep v10.3.2
  CHANGELOG.md
  example/ios/Podfile.lock
  package.json
  react-native-smile-id.podspec
Labels: Review effort 1/5
